---
layout: post
title:  Course à pied et C25K
---

<p><div style="color:red;text-align:right;">Ayé, c'est fini \o/, n'hésitez pas à aller voir le <a href="#update-2013-11-01--bilan-et-pause-hivernale-">bilan de cette épopée</a> !</div></p>

== Kezako le C25K ?

C25K = "couch to 5km" = "du canapé jusqu'à cinq kilomètres". Le but ? Que quelqu'un qui n'a pas l'habitude de faire de sport travaille régulièrement (3x par semaine) et progressivement (effort qui augmente de semaine en semaine) pour être au final capable de courir 5km d'une traite au bout de 9 semaines (personnellement je table sur le double)

== Pourquoi se faire du mal ?

Ma frangine préférée s'y est mise le 1er avril (c'était pas une blague !) et du coup je me suis dit "pourquoi pas". D'autant plus que je n'ai plus de vélo car pas de place à Paris pour le ranger, et que depuis 2 ans je manque un peu de partenaires pour aller au badminton. Bref, ça va faire 3-5 ans que je ne fais quasiment plus aucune activité physique réelle, si ce n'est marcher 2x 20 mins par jour pour les A/R au boulot. Tout en aimant trop la bouffe pour résister à mes envies. Je suis donc un très bon cobaye pour ce truc !

Le programme est disponible link:http://www.c25k.com/c25k_french.htm[en français], et de plus sur link:http://www.reddit.com/r/C25K/wiki/faq[ce lien] il y a pleins de références vers les applications mobiles pour avoir les consignes par dessus la musique perso de son smartphone, ou des podcasts directement pour les baladeurs, etc.

Mais en résumé, **il faut juste de la volonté et 30 minutes 3x/semaine**... simple non ?

J'emprunte le link:http://www.play2run.com/sport/43-rs4.html[baladeur-casque RS4] que Cécile utilise quand elle va à la piscine les jours où je cours pas. Il est ultra-léger et confort, et ça m'évite de se trimbaler un smartphone ou un baladeur à la main/poche ou dans un brassard. On est pas géné par les fils, on le sent pas, bref c'est top.

Ensuite, plutôt que de courir dans Montmartre avec ses foutus montées/descentes/faux-plats, et plutôt que de prendre 30 minutes de bus ou de bagnole pour aller courir dans la nature, je préfère aller au terrain d'athlétisme à côté, qui a le bon goût d'être à la fois plat, et grosso-modo à la distance nécessaire aux 5 minutes de warm-up et de cooldown.

Accessoirement, y a plus de place là bas que sur les trottoirs de Paris, et pas de gens à éviter, donc c'est no-brain sans être gavant : j'ai juste à penser à faire gaffe à ma respiration et à mes jambes, j'ai de la bonne musique dans les oreilles pour éviter de penser, et il y a des petits popotins à regarder à chaque fois que je me fait dépasser !

*2013-06-20* **Update** - Au bout de 6 séances à courir avec mes chaussures de badminton (oui c'était pas une bonne idée, mais j'ai voulu essayer) je me suis dit qu'il me fallait une vraie paire de grolles, et j'ai acheté des link:http://www.google.fr/search?q=nike+air+pegasus%2B+29[Nike Air Pegasus+ 29] que j'avais trouvées en solde à 59 euros au lieu de 110, et c'est le jour et la nuit côté confort et amorti. Je suis heureux.

*2013-08-24* **Update** - Après une quinzaine de sorties, même quand je fais attention et/ou que je met de la link:http://www.google.fr/search?q=creme+nok[Nok] pour pas que ça frotte aux cuisses, je finissais par avoir mal et la peau des cuisses irritée et j'ai donc décidé d'acheter un link:https://www.google.fr/search?q=cuissard+course+%C3%A0+pied+homme[cuissard] à 20 euros piece : résultat, je n'ai plus ni frottement ni gène ni irritation ni douleur, et le tout sans utiliser de crême anti-frottement, c'est le pied. Je suis trop con de pas l'avoir fait avant. En plus il paraît que ça me fait des belles fesses...

*2013-09-22* **Update** - J'ai une link:https://fr.wikipedia.org/wiki/Communication_inter-ventriculaire[CIV] depuis la naissance, donc je connais mes limites et je sais quand lever le pied. Mais à part le feeling, je n'ai aucune "mesure" objective pour aller avec. Donc plus par caprice/curiosité que nécessité, je me suis acheté un link:http://www.decathlon.fr/cardio-onrhythm-100-noir-id_8051265.html[cardio] à 22 euros chez décathlon. Et vu qu'il fait aussi chrono, j'ai pu vérifier la cohérence de l'affichage des BPM avec la réalité en comptant manuellement les battements sur une durée fixe. Résultat : assis à mon bureau il affiche 52 BPM, et je compte 154 battements en 3 minutes soit 51.3 BPM donc c'est OK.  Juste après une séquence de 5 minutes, je vérifie avec le chrono (en continuant de marcher pour pas que ça retombe trop vite) et je compte 77 battements en 30 secondes soit 154 BPM contre 160 pour le cardio donc c'est à nouveau correct. Accessoirement en marche (très) rapide lors du warm up je tourne à 100 BPM, lors des 3 premières minutes de course tranquille je tourne à 130 BPM, et à la fin de chaque bloc de 5 minutes, je suis à 160 BPM, chiffre qui reste stable durant l'effort. Pour finir le chrono confirme l'estimation faire sur timings du podcast W4 où je fais 2 tours de link:http://www.gmap-pedometer.com/?r=2210496[piste] en 3 minutes : là le chrono dit 4:28 pour exactement 3 tours, soit 2.77m/s et ~10km/h.

*2013-10-02* **Update** - Aujourd'hui j'ai couru 5km d'une traite (détails plus bas) ! Donc bilan rétrospectif de mon entraînement jusqu'ici : W1 + W1 + W2 + W2 + W3 + W3' + W3" + W4 + W4 + W5 + W5 = 11 semaines de programme, étalées sur 5 mois calendaires dont 2 fois 1 mois de pause plus 1 semaine de vacances. En tout cas je continue le programme pour consolider, fiabiliser, et poursuivre la progression.

== Update 2013-11-01 : Bilan et pause hivernale !

Dehors il fait froid, et ça finit par faire mal à la gorge. Déjà que je toussotte depuis avant-hier (alors que j'ai toujours un col montant quand je sors) j'ai décidé que je refuse de tomber malade en allant courir dehors par ce temps.

*Bref, certes je clos mon C25K avec quelques jours d'avance, mais l'objectif est rempli \o/ : je cours 30 minutes sans difficultés réelles et ce de manière très régulière (tous les 2j)*

Rétrospectivement, je pense que le plus dur est de passer de la W3 à la W4. Et tout est devenu plus simple depuis que je respecte absolument un rythme de sortie fixe. Par contre je ne me suis jamais interdit de faire plus (ou moins) que le programme attendu pour une séance en particulier : ça permet de pas se mettre martel en tête, d'éviter les déceptions, et surtout de pas forcer. En résumé, pour moi être régulier dans la pratique est plus important qu'être régulier dans la "performance"

*Un grand merci à ceux qui m'ont montré que c'était possible, à ceux qui m'ont supporté, et bon courage à ceux qui tenteront le coup : on en chie, mais au final on se sent mieux !*

Durant l'hiver je vais essayer de "nager" plutôt que de "courir", et ce même si aller à la piscine prends plus de temps, de trajet et de logistique que de sortir courir. Et ce bien sûr toujours tous les 2j, c'est vital pour moi de savoir que je suis capable de tenir une routine. La piscine, ça devrait me permettre d'une part de faire travailler mon corps autrement, mais aussi de faire quelque chose de moins brusque pour les chevilles et genoux et ce afin d'anticiper d'éventuels problèmes. Ca me permettra surtout de travailler le souffle, qui était souvent le facteur limitant plutôt que les muscles dès que je cherchais à hausser le rythme.

Et qui sait, au printemps envisager de travailler l'objectif des 10km ? Wait'n'see :-)

== Récapitulatif

Sorties et impressions
- 2013-05-06 **W1-1** : toute première séance, 8x( 60s course + 90s marche ) j'arrive au bout "juste juste" côté souffle
- 2013-05-08 **W1-2** : dès que je respire plus posément, j'arrête d'être essouflé
- **pause** : j'ai pas le moral suite à la disparition d'link:/2013/05/13/notre-petite-isis-nous-a-quittes.html[Isis] et j'ai aucune envie de faire des efforts
- 2013-06-12 **W1-3** : retour et reprise sur Paris, je finis la séance content d'avoir bossé
- 2013-06-14 **W1-4** : cette fois-ci, ça passe sans trop d'efforts
- 2013-06-16 **W1-5** : là c'était carrément easy-mode, step up !
- 2013-06-20 **W2-1** : Les nouvelles shoes c'est topissime. Ca tombe bien parce que je passe à 6x (90s course + 120s marche) et j'ai les mollets en feu en début de séance, mais ça va mieux à la fin curieusement.
- 2013-06-23 **W2-2** : finalement ça fait du bien d'avoir du mal, ça passe tout juste
- 2013-06-26 **W2-3** : j'ai les mollets qui tirent au début, et une sensation dans un genou sur la fin
- 2013-06-28 **W2-4** : la gène aux mollets s'ammoindrit, par contre gène au tendons du genoux
- **pause** : j'ai un douleur au tendon du genoux gauche s'en va pas, je décide de stop jusqu'à disparition
- 2013-07-25 **W1-6** : il aura fallu plus de 3 semaines, mais je sens plus rien depuis 1 semaine donc confiant je repars sur une W1 tranquilou, easy :-)
- 2013-08-01 **W2-5** : petite séance W2 en vacances à Quiberon sur le front de mer
- 2013-08-07 **W2-6** : bête comme je suis, j'essaie de courir "jusqu'à ce que je puisse plus". Ca se passe très bien pendant 8 minutes d'affilée (omg !) puis j'ai un point de côté, je continue la séance au rythme du podcast, mais j'écourte pour compenser le temps de course de ma bétise du début.
- 2013-08-16 **W2-7** : de retour à Paris, en pleine chaleur, côté muscles des jambes ça va nickel, respiration easy, mais j'ai grave mal à la peau des cuisses et ça me met super en rogne.
- 2013-08-18 **W3-1** : En congé, c'est l'opportunité de monter d'un cran : 2x ( 90s course + 90s marche + 180s course + 180s marche ) ... la première 3 minutes, j'ai fini au mental en comptant les secondes : il y a moins d'air frais que sur la côté sauvage en bretagne, et j'ai l'impression de pas respirer ! Je m'accroche et je pense à rien, et ça passe. Grosse satisfaction d'y être arrivé.
- 2013-08-21 **W3-2** : J'aime pas la fin du podcast W3. Ca fait 180s course + 180s recovery + 300s cooldown... trop de marche à la fin. Du coup d'insère 90s de course en bonus entre recovery et cooldown.
- 2013-08-24 **W3-3** : J'ai acheté un cuissard, et OMG c'est le pied, plus rien qui frotte je suis heureux ! Séance pleine d'efforts, et re-90s de course en bonus avant le cooldown. C'était cool.
- 2013-08-26 **W3-4** : Plus d'hésitation à sortir car plus de frottements. Je me sens bien, content de mon effort. Re-90s de course en bonus avant le cooldown.
- 2013-08-28 **W3-5** : Sorti à 20h, vent frais, c'est la grande forme, ce coup ci je glisse 5 minutes course avant le cooldown. Content :-)
- 2013-08-30 **W3-6** : Sorti à 16h, il fait chaud et ça change la donne. Séance plus dure, mais ça passe quand même, et je fais 180s de bonus avant cooldown.
- 2013-09-01 **W3-7** : Sorti à 15h30, je sens mes mollets pendant toute la séance, on dirait que je paie la bonne bouffe de la réunion de famille d'hier... Je rajoute 5 mins de course avant le cooldown. Au vu du contenue de la W4 je pense que c'est plutôt une bonne idée d'avoir fait ça, on verra bien.
- 2013-09-03 **W3-8** : Ce soir environ 40 personnes sur la piste, c'était impressionnant. Et au lieu de faire 90c-90m-180c-180m-90c-90m-180c-180m-300c comme les derniers jours, j'ai fais 90c-90m-180c-90m-180c-90m-180c-180m-300c ... donc autant au total, mais par blocs plus long et avec moins de recovery entre chaque, un peu comme ce que je vais subir dès que je comencerai la W4
- 2013-09-05 **W3-9** : Y faisait chaud ce soir à 20h15, et pas un souffle d'air. Je respire mieux quand je m'entends respirer par dessus la musique, donc faudra que je pense à baisser le son.... sinon Même programme que la dernière fois, et c'est décidé, la W4 ça sera pour ce week-end.
- 2013-09-08 **W4-1** : Mon dieu que je suis content... Avec ma préparation "bonus" j'ai fais ma première séance W4 avec presque les mêmes sensations que la séance précédente. Et passer de 14 mins (W3+5mins) à 16 c'est quand même plus simple que de 9 (W3 standard) à 16 !
- 2013-09-10 **W4-2** : Beaucoup moins chaud que les autres jours, mais je trouve que ça fait pas de différence : j'ai chaud et je transpire. Séance OK avec quelques sensations d'inconfort dans les genoux.
- 2013-09-12 **W4-3** : Il a plu, séance fraîche, peu de monde
- 2013-09-16 **W4-4** : Courir sous la pluie (en fin de séance) c'était pas si pire que ça. Et il fait presque froid comparé aux 34 degrés d'il y a 10 jours ! J'avais sauté une séance, léger inconfort dans le genoux.
- 2013-09-18 **W4-5** : je pourrais faire plus de 5 minutes, et préparer la week 5, mais je respire pas régulièrement... selon que je pense à rien, ou que je réfléchisse à un truc, ou que je passe à côté de gens qui causent, je change de rythme, et ça me dérègle un peu. On s'en fout, je fais mes 16 mins avec plaisir.
- 2013-09-20 **WTF** : séquence brainfuck, j'avais 25 mins de marge avant le rdv de ce soir, résultat colis suspect dans la A + incendie dans la 13 après coup, donc je décide de courir 2x8 plutôt que 3+5+3+5... tout ça pour au final me dire ... *SCREW THIS !* et hop, 5 mins de chauffe, 22 minutes de courses d'une traite comme ça bim bam boum, puis cooldown. Un peu moins vite que d'habitude, certes, mais c'est passé presque sans difficulté réelles. Bon je suis crevé hein, défoncé par la semaine qui a été longue, m'enfin je suis aussi supris que content.
- 2013-09-22 **W5-1** : Nouvelle semaine qui sera cette fois ci progressive de séance en séance, et on commence par 3x5mins ce qui est plutôt cool après l'effort intense de vendredi. Ce coup-ci j'y vais le matin avant le déj' et avec mon nouveau cardio, pour plus de détails voir l'update plus haut.
- 2013-09-24 **W5-2** : Après une journée de merde, ces 2x8 mins, ça déstresse...
- 2013-09-26 **W5-3** : De nouveau une longue séance (1x20 minutes) où j'ai fais 1x19mins (12 tours) + 1x3mins (2 tours). Comme 5km ça fait exactement 20 tours, je m'étais donc dit je fais les 20 minutes de la séance, et si je peux je continue pour voir combien il me "manque". Sauf qu'à la fin de ces 2 tours supplémentaires j'ai eu d'un coup une douleur moyenne tout en haut de la cuisse gauche face avant, à chaque fois que je ramène la jambe vers l'avant, et j'ai donc stoppé direct. Ca continuait de me gêner durant les 5 minutes de cooldown (boitillement) mais ça a disparu dès que j'a fais mes étirements habituels une fois arrivé à la maison. J'en déduis que le fractionné court c'est bien, mais le fractionné long c'est pas bien :-) Sinon, ma pensée du jour ça a été "super 14 tours de faits, ne reste plus qu'à réussir à faire 6 tours en plus". Ce qui parait "peu"... sauf quand on réalise qu'il s'agit en fait de faire ~50% d'efforts de plus que ce que je fais déjà... M'en fiche, je suis pas pressé !
- 2013-09-28 **W5-4** : Samedi matin, après un bon petit déj' (1 café + 2 croissants) on sort ensemble faire chacun notre séance... je sais pas si le temps est lourd, ou si c'est le déj' (d'habitude je cours le soir avant de dîner, soit +5 heures après un repas et j'ai donc le ventre bien vide) mais mon dieu que ces 3x5 minutes ont été difficiles.
- 2013-09-30 **W5-5** : 10+8 au lieu de 8+8, car j'ai pas fait gaffe au chrono. J'étais sorti tôt du boulot et il faisait frais, mais ça m'a tiré dans les mollets pendant toute la durée. Après-demain c'est de nouveau la "séance épreuve", on verra bien ce que ça donne.
- 2013-10-02 **W5-6** : aujourd'hui je devais faire 20 minutes, et l'objectif est largement rempli ! A 17'25" j'étais à 10 tours, et je me disais "reste plus qu'à refaire la même chose pour faire cinq bornes" ; à 20 mins (11 tours 1/2 environ) je me sentais bien, il faisait pas chaud, et j'étais allé suffisement "lentement" (8.5km/h en moyenne au lieu du 10 km/h lors du fractionné) pour avoir la capacité de continuer sans forcer, alors j'ai continué. Vers 14tr/25min j'ai eu un inconfort dans le genoux gauche et la cheville droite, mais en étant un peu plus souple ça a disparu et ça m'a pas gêné ; à 30min/17tr ça allait bien mais je sentais que j'étais en "no-man's land" côté muscles et je ne savais pas à quoi m'attendre. J'ai fais les trois derniers tours avec un sourire même pas grimaçant, mais \o/ BINGO \o/ : 20 tours = 5km. J'aurais pu continuer encore un peu, mais je sais pas du tout combien de temps donc je vais pas être présomptueux. Mais le pire dans cette histoire, c'est que le même jour au même moment, ma soeur était contente car elle avait réussi elle aussi à courir 35 minutes (20+10+5) ! Bref, tout le monde est super content et fier de moi :-)
- 2013-10-05 **W6-1** : Début semaine 6, 5+8+5. Un peu mal à au muscle de devant de la cuisse droite, c'est un reste de la dernière fois que je paie. Je suis sorti le matin (~2h après le déj) et ça change pas : je rame plus que quand j'y vais le soir.
- 2013-10-07 **W6-2** : 10+10, et il paraîtrait que le truc qui me fait "mal" c'est le muscle link:http://www.corpshumain.ca/images/Muscles_jambe1_%28FF%29.jpg[illiaque]. Je me coucherai moins con ce soir :-)
- 2013-10-09 **W6-3** : 25'44" = 16 tours = 4km = 9.32km/h. Fini sous un petit crachin, pas désagréable sauf que ça fait couler la sueur dans les yeux et que ça pique. Pensée du jour : c'est fou ce que le corps est capable de s'adapter, il y a 5 mois j'étais éssouflé au bout de 100m et mort au bout d'un tour...
- 2013-10-11 **W7-1** : 25'03" = 16 tours = 4km, par temps froid "winter is coming". Muscle cuisse droite un peu gênant sur la fin, comme d'habitude. Mais surtout la grande nouvelle du jour, c'est que ma soeur préférée a participé à link:http://www.lastrasbourgeoise.eu/[la Strasbourgeoie] 2013 ! Départ 20h45, toute stressée pour l'évènement final de son programme, elle a finit la boucle de 5km sans marcher et en 44' ! On est super-méga-hypra fiers d'elle d'être arrivée au bout de son projet, bravo frangine !
- 2013-10-13 **W7-2** : 25'08" = 4km, juste après jus d'orange + muffin anglais grillé + confiture myrtille, miam. Pas trop dur pour un matin. Je viens d'avoir le premier "défaut" de mon cardiotruc, et le fait qu'il soit analogique et non digital. Il devait y avoir quelqu'un sur la piste qui en avait un aussi analogique, parce que de temps en temps il faisait le yoyo : des 140-150 habituels, ça tombait à 90, remontait à 110, mais pas tout le temps, environ 1 tours sur deux. Ca devait correspondra à quelqu'un à proximité. Bref, ou alors c'est la pile de la ceinture, mais j'y crois pas vraiment. On verra ça les prochaines fois.
- 2013-10-15 **W7-3** : 25'33" = 4km. Dur journée, j'ai ramé ce soir. La prochaine c'est 18 tours, soit 4.5km. Je me connais, je vais faire 18, et je vais pas pouvoir m'empêcher de faire les 2 de plus pour arrondir...
- 2013-10-17 **W8-1** : 27'11" = 18 tours = 4.5km, puis comme anticipé, j'ai fais 2 de plus, et on arrive à 30'22" = 20 tours = 5km. Soit 5 minutes de moins que la première fois où j'ai fais 5km deux semaines plus tôt, mais il y a une explication : ce soir j'ai commencé par deux tours de chauffe, puis j'ai fais 4 tours = 1km genre "vite". Donc 5'08" au lieu de 6'20" habituel. Me demandez surtout pas pourquoi j'ai fait ça j'en sais rien, je me suis juste mis à accélérer sans y penser, avec des grandes enjambées et j'ai mis un tour pour m'en rendre compte. Bref, j'étais bien entendu complètement essoufflé au bout des 4 tours, mais j'ai récupéré après en trottinant, hors de question de marcher. Je suis arrivé au bout, pas trop trop cassé, mais plutôt à 150 bpm qu'à 140.
- 2013-10-19 **W8-2** : 26'45" = 18 tours = 4.5km. Pas eu envie d'aller plus loin, j'avais déjeuné 1h&#189; avant mais c'est pas suffisant : j'ai ramé, même si je suis allé plus vite au final (j'avais pas mis le cardio aujourd'hui, donc j'étais surement plus haut que d'habitude)
- 2013-10-28 **W8-3** : 29'17" = 18 tours = 4.5km. Après une semaine d'arrêt (maladie), reprise. Quand je vois le chrono, je me dis que je me suis traîné, mais j'ai pourtant pas eu l'impression de m'être économisé...
- 2013-10-30 **W9-1** : seulement 14 tours = 3.5km = 20'10". J'ai eu une gêne qui pouvait vite devenir très douloureuse dans un coin du genoux gauche, alors j'ai arrêté dès que j'ai fini mon tour. La différence par rapport à d'habitude c'est que j'ai "couru lentement" plutôt que "trottiné vite" ... même si c'est pas très clair comme explication. Quand je "trottine vite", je fatigue moins, le coeur bat moins vite, mais les jambes battent plus rapidement et ça fait pleins de petits enjambées ; alors que quand je "cours lentement" j'ai les jambes qui battent plus lentement, des plus grandes enjambées et le coeur qui est plus haut et le souffle moins facile ; dans les deux cas j'avance à peu près à la même vitesse. Bref, en "courant" je pense que les genoux subissent beaucoup plus et que ça vient de là. Dès que j'ai arrêté de courir ça a disparu, mais mon genoux fait "clic clic" maintenant.
- 2013-11-01 **bilan** : "The End", hiver, piscine... voir le link:#update_20131101__bilan_et_pause_hivernale_[bilan] !

