--
layout: post
title: Serveur DNS personnel, le retour !
--

:toc:
:toc-title: Table des matières

Cet article est un mémo permettant de configurer des serveurs DNS faisant authorité sur une ou plusieurs zones, et qui seront utilisés à la place des serveurs du fournisseur de nom de domaine. À noter qu'il est important de respecter l'ordre des étapes et des vérifications.

== Pre-requis

Matériel

* disposer de _deux_ hôtes Linux au minimum
* chacun disposant d'une adresse IPv4 externe _fixe_
* chacun disposant d'une adresse IPv6 externe _fixe_
* chacun joignable depuis internet sur les ports UDP 53 et TCP 53
* chacun pouvant se joindre entre eux sur les même ports
* chacun ayant un "reverse-DNS" IPv4 et IPv6 pointant sur leur noms DNS

Noms de domaine

* disposer d'un (ou plusieurs) noms de domaines
* le bureau d'enregistrement de ces noms de domaine doit :
** permettrent d'utiliser ses propres serveurs DNS
** permettrent de positionner nos signatures DNSSEC ("DS records")

Logiciels

* installer `bind9` sur chaque serveur (version 9.10.3)

Informations annexes

* j'utilise OVH comme fournisseur de nom de domaine
* j'utilise la distribution Ubuntu 16.04 LTS (avec bind 9.10.x)

La suite s'appuie sur l'ensemble des points ci-dessus. Si votre situation diffère, à vous de faire le nécessaire pour adapter.

== Documentation

* link:https://www.isc.org/downloads/bind/doc/[Bind9 documentation]
* link:https://ftp.isc.org/isc/pubs/tn/isc-tn-2002-2.html[How to configure and authorative-only nameserver]
* link:https://ftp.isc.org/isc/dnssec-guide/html/dnssec-guide.html[How to configure DNSSEC guide]
* link:https://tools.ietf.org/html/rfc6781[DNSSEC best practices IETF]
* link:https://www.enisa.europa.eu/publications/gpgdnssec[DNSSEC best practices ENISA (eu)]
* link:https://csrc.nist.gov/publications/detail/sp/800-81/rev-1/archive/2010-04-30[DNSSEC best practices NIST (us)]
* link:https://linux.die.net/man/8/dnssec-keygen[Man page de dnssec-keygen]
* link:https://www.cloudflare.com/dns/dnssec/how-dnssec-works/[cloudflare dnssec guide]
* link:https://www.iana.org/assignments/dns-sec-alg-numbers/dns-sec-alg-numbers.xhtml[DNSSEC Algorithm numeric values]

== Variables

Ci-après, mes éléments de configuration (à adapter, bien sûr !)

----
# un des noms de domaine gérés par nos serveurs
export DOMAIN="nipil.org"

# le répertoire où les clés utilisées seront stockées
export KEYDIR=/etc/bind/keys/${DOMAIN}

# les caractéristiques cryptographiques sont définies dans les bonnes pratiques
# https://ftp.isc.org/isc/dnssec-guide/html/dnssec-guide.html#signing-easy-start-generate-keys
export KEY_ALGO=RSASHA256
export KSK_SIZE=2048
export ZSK_SIZE=1024

# l'adresse IPv4 externe du serveur qui sera maître
export IPV4_MASTER="37.187.7.187"
# l'adresse IPv6 externe du serveur qui sera maître
export IPV6_MASTER="2001:41d0:a:7bb::1"
# l'adresse IPv4 externe du serveur qui sera slave
export IPV4_SLAVE="91.121.167.150"
# l'adresse IPv6 externe du serveur qui sera slave
export IPV6_SLAVE="2001:41d0:1:e896::1"

# le nom dns complet du serveur maître
export MASTER_NAME="axis"
# le nom dns complet du serveur slave
export SLAVE_NAME="isis"
# le nom dns complet du serveur maître
export MASTER_FQDN="${MASTER_NAME}.${DOMAIN}"
# le nom dns complet du serveur slave
export SLAVE_FQDN="${SLAVE_NAME}.${DOMAIN}"
----

Dans l'ensemble des commandes suivantes, on remplacera les variables par les valeurs correspondantes (utiliser celles pour *votre* environnement !)

== Clés DNSSEC

On crééra une clé de signature de zone (`ZSK`) _active_ qui signera les entrées (`A`, `CNAME`, `TXT`...) du nom de domaine, ainsi qu'une clé de signature de clé (`KSK`) _active_ qui signera toutes les clés `ZSK`

----
mkdir -p -v ${KEYDIR} && \
dnssec-keygen -a ${KEY_ALGO} -b ${ZSK_SIZE} -K ${KEYDIR} ${DOMAIN} && \
dnssec-keygen -a ${KEY_ALGO} -b ${KSK_SIZE} -K ${KEYDIR} -f KSK ${DOMAIN} && \
find ${KEYDIR} -type f | xargs chown -v root:bind && \
find ${KEYDIR} -type f -name '*.key' | xargs chmod -v 644 && \
find ${KEYDIR} -type f -name '*.private' | xargs chmod -v 640
----

Pour info, le premier chiffre dans le nom d'une clé correspond à la représentation de l'algorithme utilisé, le deuxième nombre est l'identifiant de la clé :

Ce sont les clés privées (les fichiers `.private`) qui contiennent les dates de validité de la clé concernée. On peut les consulter et les modifier avec la commande `dnssec-settime` :

----
dnssec-settime -p all Knipil.org.+008+26493.private
Created: Thu Oct  5 06:25:46 2017
Publish: Thu Oct  5 06:25:46 2017
Activate: Thu Oct  5 06:25:46 2017
Revoke: UNSET
Inactive: UNSET
Delete: UNSET
----

----
dnssec-settime -p all Knipil.org.+008+32707.private
Created: Sat Oct  7 15:16:42 2017
Publish: Sat Oct  7 15:16:42 2017
Activate: Sat Oct  7 15:16:42 2017
Revoke: UNSET
Inactive: UNSET
Delete: UNSET
----

Ce sont les clés publiques (les fichiers `.key`) qui contiennent le type de la clé concernées, et l'empreinte qui sera utilisée pour publier les `DS record` dans la zone parente :

----
cat Knipil.org.+008+26493.key
; This is a zone-signing key, keyid 26493, for nipil.org.
; Created: 20171005062546 (Thu Oct  5 06:25:46 2017)
; Publish: 20171005062546 (Thu Oct  5 06:25:46 2017)
; Activate: 20171005062546 (Thu Oct  5 06:25:46 2017)
nipil.org. IN DNSKEY 256 3 8
    AwEAAbnimJ65KZhcH1WjoTxMhus6diIExGryJmNNzp8c2/kuGDVYFL+l
    uviQWz2C+Lj+Z1lzRZ89mgxhZs9ZjpLJSbIxfo4R+ayW5pj+XJVTaVm5
    2N2vgNNsY/qWl2oPxitWLkt0Ore7pHmf3hI1eL6QWYNmoqK/yUKQw7q1
    hICsJZ/3
----

----
cat Knipil.org.+008+32707.key
; This is a key-signing key, keyid 32707, for nipil.org.
; Created: 20171007151642 (Sat Oct  7 15:16:42 2017)
; Publish: 20171007151642 (Sat Oct  7 15:16:42 2017)
; Activate: 20171007151642 (Sat Oct  7 15:16:42 2017)
nipil.org. IN DNSKEY 257 3 8
    AwEAAcZpaxDC2FTSRrY4byNOZzaONLUcnwm2VID+SscCE6D2LFOMiaSU
    8O6ULTTy6FgEliI1zaYNgWf+tcNvQHayOjaaEuKSDIvuO+MkO0zd2RK8
    nMpyt/9uCXwaBjKZ+ZYnpiBimKV00FCsns06V5oBD5sQVDvpN3R6L5sG
    mbvx14433mzQzB41bG0onI3e2tp8+3nk9HKwaouhzw7bmw75o6YClvAK
    Ftbh7AlzW4foi4U+3Lx2siu8sxVyMLRBYjbY041K/Sy1k14abMh3+BB8
    4moaXBe19SMkVNTODkEzKFJWc2A3NIPIoNREcmUzBYoMi0etpXr9JFeC
    gG2/1OTKYI0=
----

== Configuration maître

.named.conf.options
----
options {
    directory "/var/cache/bind";
    dnssec-validation auto;
    auth-nxdomain no; # conform to RFC1035
    listen-on-v6 { any; };
    allow-query { any; };
    allow-transfer {
        localhost;
        ${IPV4_SLAVE};
        ${IPV6_SLAVE};
    };
    recursion no;
};
----

.named.conf.local
----
zone "${DOMAIN}" {
    type master;
    file "/var/cache/bind/db.${DOMAIN}";
    key-directory "/etc/bind/keys/${DOMAIN}";
    inline-signing yes;
    auto-dnssec maintain;
};
----

On configure chaque zone de manière minimale :

./var/cache/bind/db.${DOMAIN}
----
$TTL 5M
@ IN SOA ${MASTER_FQDN}. postmaster.${DOMAIN}. (
  56   ; serial
  4H   ; refresh
  1H   ; retry
  1W   ; expire
  3H ) ; minimum
@              IN   NS     ${MASTER_FQDN}.
@              IN   NS     ${SLAVE_FQDN}.
${MASTER_NAME} IN   A      ${IPV4_MASTER}
${MASTER_NAME} IN   AAAA   ${IPV6_MASTER}
${SLAVE_NAME}  IN   A      ${IPV4_SLAVE}
${SLAVE_NAME}  IN   AAAA   ${IPV4_SLAVE}
----

== Vérifications master

On vérifie la zone

----
named-checkzone ${DOMAIN} /var/cache/bind/db.${DOMAIN}
----

On vérifie la configuration

----
named-checkconf -z
----

On recharge la configuration

----
rndc reload
----

On demande la signature de la zone

----
rndc sign ${DOMAIN}
----

Pour information, le serial de la version signée transmise aux slaves est en avance sur le serial de la version non-signée, on le voit dans le log bind sur le master :

----
named[8251]: zone nipil.org/IN (signed): serial 17 (unsigned 14)
----

On vérifie le transfert de zone en local

----
dig @localhost ${DOMAIN} axfr
----

On prendra soin de consulter le log (généralement `syslog`) pour voir l'ensemble des message (éventuellement d'erreur) liés au process `bind` !





















on vérifie que tout est bon au niveau de notre serveur master :

export ZONEKEYFILE=$(grep -L 'zone-signing key' /etc/bind/keys/${DOMAIN}/*.key | head -n1)

grep DNSKEY ${ZONEKEYFILE} | sed -r -e 's|(\S+)\s\S+\s\S+\s(\S+)\s(\S+)\s(\S+)\s(.*)|trusted-keys { \1 \2 \3 \4 "\5"; };|' > /tmp/test-${DOMAIN}.key

delv @localhost -a /tmp/test-${DOMAIN}.key +root=${DOMAIN} ${DOMAIN}. SOA +multiline

; fully validated
nipil.org.              10800 IN SOA nipil.org. hostmaster.nipil.org. (
                                52         ; serial
                                10800      ; refresh (3 hours)
                                3600       ; retry (1 hour)
                                604800     ; expire (1 week)
                                10800      ; minimum (3 hours)
                                )
nipil.org.              10800 IN RRSIG SOA 8 2 10800 (
                                20171104064746 20171005054746 26493 nipil.org.
                                DdQzLqi4G7217EATJwcoDHKZTEnkx7AJLmtI272FNBGj
                                XZ7yaANan0stQhFvrKC4rd0Stf14U63n6nZ1IUJdBWkA
                                cXRPwFHPpg2efTy3NifjFYnxIMWm4MxDQCTS34mxuaaC
                                G3Enr5d6S0jx9N9H1RXGLomN+JOZ8WmlX06eRtw= )


Maintenant que tout est OK, on doit effectuer la dernière action : construire la chaine de confiance, en fournissant à notre registrar (à qui on paie le nom de domaine) les éléments nécessaires pour établie la "chain of trust".




$TTL 3600
@       IN SOA dns108.ovh.net. tech.ovh.net. (2017091200 86400 3600 3600000 300)
                                  IN NS     ns108.ovh.net.
                                  IN NS     dns108.ovh.net.
                                  IN MX 1   mx1.ovh.net.
                                  IN MX 100 mxb.ovh.net.
                                  IN MX 5   mx2.ovh.net.
                               60 IN A      91.121.167.150
                               60 IN AAAA   2001:41d0:1:e896::1
                                  IN TXT    "google-site-verification=TVJXmi4nS4cuWfsgYujfQ3MjT0h9b1_MG1sIYROam7w"
                              600 IN TXT    "v=spf1 include:mx.ovh.com -all"
2016-06-13._domainkey.isis     60 IN TXT    "k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDxEIFLzsFqLNlqiIluZkn0TxgBo74d5y0szafcdIGB7bJgCFUyMtvKX6xDk7AmvkFrqy7357rpM8d3lqiBTb8Z9Rs+xSuTk50TmxXFrPswm1ah2CQJUc+gaiCPgu97vU5Q3S57nNai0XEFMk7aHzpblLe5hAheGJt+SGzvDbfQVwIDAQAB"
_dmarc                            IN TXT    "v=DMARC1; p=none; pct=100; rua=mailto:postmaster@nipil.org;"
_dmarc.isis                    60 IN TXT    "v=DMARC1; p=reject; pct=100; rua=mailto:postmaster@isis.nipil.org;"
axis                              IN MX 10  axis.nipil.org.
axis                              IN A      37.187.7.187
axis                              IN AAAA   2001:41d0:a:7bb::1
axis                          600 IN TXT    "v=spf1 mx -all"
home                              IN CNAME  homenipilorg.ddns.net.
isis                              IN MX 10  isis.nipil.org.
isis                              IN A      91.121.167.150
isis                              IN AAAA   2001:41D0:1:E896::1
isis                          600 IN TXT    "v=spf1 mx -all"

$ dig nipil.org +trace

; <<>> DiG 9.10.3-P4-Ubuntu <<>> nipil.org +trace
;; global options: +cmd
                       454727  IN      NS      e.root-servers.net.
                       454727  IN      NS      j.root-servers.net.
                       454727  IN      NS      k.root-servers.net.
                       454727  IN      NS      a.root-servers.net.
                       454727  IN      NS      d.root-servers.net.
                       454727  IN      NS      i.root-servers.net.
                       454727  IN      NS      h.root-servers.net.
                       454727  IN      NS      m.root-servers.net.
                       454727  IN      NS      c.root-servers.net.
                       454727  IN      NS      l.root-servers.net.
                       454727  IN      NS      f.root-servers.net.
                       454727  IN      NS      g.root-servers.net.
                       454727  IN      NS      b.root-servers.net.
                       518385  IN      RRSIG   NS 8 0 518400 20171018050000 20171005040000 46809 . Gqx4rurS7g34OaTMZuVqeULR0YKkHJSDbeq6MhUrf2Zs9k4S+EfYYTun 9qcns+xkDlrHkcrPYMQpOjRTLHXasaZnWcnr+t2ok7MlGefnLT8OCZBh UDcDw0gO/0V4oPn6R9dkTA7l2ZOaQl5UdHh1E6GRynr5JDaqZp5R0iX3 PZaaR9oL9GxvTW5cED4C5auIVt4TCOLSuaeotMyuuNKlVUXZkAXGHKtz Nqpzj0cm+NWMATzqOHT1yJzh9BoB1POZdMNIhsksyyX3idDu4VAQIrwR zeQdHPIZhrJ4Hc+7JVEkLC6tXI56GVb+eBlFY1Q6q0M1zWi7+DjcGJJU fjsVzA==
;; Received 525 bytes from 127.0.1.1#53(127.0.1.1) in 9 ms

org.                    172800  IN      NS      b0.org.afilias-nst.org.
org.                    172800  IN      NS      a0.org.afilias-nst.info.
org.                    172800  IN      NS      c0.org.afilias-nst.info.
org.                    172800  IN      NS      b2.org.afilias-nst.org.
org.                    172800  IN      NS      d0.org.afilias-nst.org.
org.                    172800  IN      NS      a2.org.afilias-nst.info.
org.                    86400   IN      DS      9795 7 1 364DFAB3DAF254CAB477B5675B10766DDAA24982
org.                    86400   IN      DS      9795 7 2 3922B31B6F3A4EA92B19EB7B52120F031FD8E05FF0B03BAFCF9F891B FE7FF8E5
org.                    86400   IN      RRSIG   DS 8 1 86400 20171018050000 20171005040000 46809 . WCtyce7S1hwxD/yirA2kl0M4RBD3ijxAJrgyQ1pOrNAJR7tyzpPC8Tsl njkvLQ0sRR4LEco2INvHNUZgvpaVEggNpvux6bL5RMJ99YaE6q/PqF2j ufLHsVChfzFUEhYaeeGOtPCii+fyYc/6J4xsSts+PiH2scHuAlwF1zE6 CM8bif9MjIaiKwF7jNBhftkEgYhsWoNsdH01zyOf0kE65BPeSdClCl/B xRhdNLUYlTYqe0ox6MHpsAUZnV1aluBiQ0gLV7zLhn6y6C1mTpH0lWAF H3oPKbXswo3ipc9raHo7oiivOi7xE2W56BlbqwDjCdjJ0mkcvXimdYzS O9q9aw==
;; Received 811 bytes from 2001:dc3::35#53(m.root-servers.net) in 20 ms

nipil.org.              86400   IN      NS      ns108.ovh.net.
nipil.org.              86400   IN      NS      dns108.ovh.net.
nipil.org.              86400   IN      DS      3285 7 2 F1197E414D0EE77097AD02AC90C5E086C99F17F11E2FC2784FE77F62 21C450ED
nipil.org.              86400   IN      RRSIG   DS 7 2 86400 20171022152331 20171001142331 3947 org. VO05V6AzTerkbDBmdg2ZjO2JCZ5EHBa7ZJf6T3jjajWxKd9x6T+zMEkF UVERADOGcPUzvr7Kh50KHHCc2CeLdpWVYAdUJhZZgnTJDrg06TLOYM8U tZkKCMPK0G5PvK1OLmeSZIDSo8u/LJx+6yKU8nssTpySINCXDUNXPG0J jrI=
;; Received 297 bytes from 199.249.120.1#53(b2.org.afilias-nst.org) in 80 ms

nipil.org.              60      IN      A       91.121.167.150
nipil.org.              60      IN      RRSIG   A 7 2 60 20171104062210 20171005062210 45578 nipil.org. uuoidYbJPncbXkJaENPgO/YYfwk+wyxX7HgQ+vbyeQ7fwVvM39NWL7DG jQRwmKmHw1aL8Pc51p5eM4srkmt7hTXIT3V65sock8XxGH/Pr5Y8mh6z EPD21ErqiuN8ULEn/1pn7XFU+L9Enl5oyMURP5iE0gNOks5ON37sjoyv vRM=
;; Received 223 bytes from 2001:41d0:1:1998::1#53(ns108.ovh.net) in 7 ms


dig org. ns

org.                    28843   IN      NS      c0.org.afilias-nst.info.
org.                    28843   IN      NS      b0.org.afilias-nst.org.
org.                    28843   IN      NS      b2.org.afilias-nst.org.
org.                    28843   IN      NS      a2.org.afilias-nst.info.
org.                    28843   IN      NS      d0.org.afilias-nst.org.
org.                    28843   IN      NS      a0.org.afilias-nst.info.

dig @a0.org.afilias-nst.info nipil.org ns

;; AUTHORITY SECTION:
nipil.org.              86400   IN      NS      dns108.ovh.net.
nipil.org.              86400   IN      NS      ns108.ovh.net.




https://docs.ovh.com/fr/fr/cloud/dedicated/dns-configuration/

ns108.ovh.net
dns108.ovh.net

https://www.zonemaster.net/


serveurs

https://docs.ovh.com/fr/fr/web/domains/generalites-serveurs-dns/
https://docs.ovh.com/fr/fr/web/domains/zonecheck-de-votre-domaine/

GLUE



https://docs.ovh.com/fr/fr/web/domains/glue-registry/





DS records



https://docs.ovh.com/fr/fr/web/domains/securiser-votre-domaine-avec-dnssec/



37.187.7.187 2001:41d0:a:7bb::1


Le script suivant permet de vérifier l'état des serveurs de la zone à laquelle est rattachée notre nom de domaine

[source]
====
#!/bin/bash
ROOTSERVER=e.root-servers.net
function get_zone {
  local __DOMAIN=${1}
  echo ${__DOMAIN} | sed -e 's/^[^.]*\.//'
}
function get_ns_from {
  local __SERVER=${1}
  local __DOMAIN=${2}
  dig @${__SERVER} ${__DOMAIN}. ns \
    | egrep "^${__DOMAIN}\.\s+\w+\s+IN\s+NS\s+" \
    | awk '{ print $5 }'
}
function check_domain {
  local __DOMAIN=${1} __ZONE __ZONESERVERS __ZONESERVER
  __ZONE=$(get_zone ${__DOMAIN})
  __ZONESERVERS=$(get_ns_from ${ROOTSERVER} ${__ZONE} )
  for __ZONESERVER in ${__ZONESERVERS}
  do
    echo ${__ZONESERVER}
    get_ns_from ${__ZONESERVER} ${__DOMAIN}
  done
}
# params
[ ${#} -eq 1 ] || { echo "Usage: ${0} domain.ext"; exit 1; }
# run
date
check_domain ${1}
====

Avant la demande,


Après la demande
